Project.toml
src/Elements.jl
src/Layout.jl
src/Stipple.jl

As discussed in #5 , I have created a PR to remove `Revise`.
I will do the same for StippleCharts and StippleUI

remove `Revise`

---

src/Stipple.jl

This refers to my last comment in #10

correction to multiuser handling

---

Project.toml

New Version: v0.9.1

---

src/Stipple.jl

unify API for components and js_methods, etc.

add js_watch, js_compute; consolidate API

---

README.md

Hi!
As discussed in #63. I just added it also to the README.
Thanks!
Felix

Add missing StippleUI to Example 2

---

src/Layout.jl
src/Stipple.jl

This is a tentative version for model-dependent deps-loading.
Not sure whether this is breaking. The idea is along the lines of what I described in #104.
Maybe we need to allow for "Strings" in DEPS keys for greater user flexibility?

fix deps loading for multi-page apps

---

src/Elements.jl
src/Stipple.jl

removed back ticks from docstring method signatures -> important for docs syntax highlighting

Removed backticks from method signatures

---

docs/src/api/stipple.md
src/Stipple.jl

Fixed some docstrings. See https://github.com/GenieFramework/Stipple.jl/discussions/99#discussioncomment-2878847.

Fixed missing docs

---

src/Stipple.jl

Required for https://github.com/GenieFramework/StippleUI.jl/pull/62

Allow separate range conversion

---

README.md

So I added `Genie.` in the example code for this to just work.

isrunning is not exported

---

Project.toml
src/Stipple.jl

fix memory leak from non-deleted models

Hh memoryleak

---

Project.toml
src/ReactiveTools.jl

Fix asset path, v0.25.17, bump genie version

---

Project.toml
src/ReactiveTools.jl
src/Stipple.jl
src/stipple/jsintegration.jl
src/stipple/reactivity.jl

Alternative rewrite of `@handlers`

Alternative rewrite of `@handlers`

---

src/ReactiveTools.jl

fix replacement of keywords

---

src/Elements.jl

Hh kw macros

---

src/ReactiveTools.jl

please don't merge @hhaensel ❌
I haven't tested this

code cleanup for lifecycle hooks 

---

src/ReactiveTools.jl

Some of the missing docstrings I added. These need to be improved in the future.

docstrings

---

src/Layout.jl

Better handling of Quasar's flexgrid

add column(), change kwargs of cell()

---

assets/js/watchers.js
src/ReactiveTools.jl
src/stipple/components.jl
src/stipple/jsmethods.jl
src/stipple/json.jl
src/stipple/rendering.jl

- support all life-cycle hooks
- support Function and Vector as result type
- fix components()

refactor js routines, support more life-cycle hooks

---

src/Pages.jl
src/ReactiveTools.jl

support for multipage app with different models/modules

---

src/Layout.jl

prepare Stipple to allow for easy integration of flexgrid kwargs in StippleUI and StipplePlotly

define flexgrid_kwargs, refactor cell, row, column

---

src/ReactiveTools.jl

fix handlers bug for mixins

---

src/ReactiveTools.jl
src/Stipple.jl
src/stipple/reactivity.jl
test/runtests.jl

This fixes the error of channel sharing mentioned in https://github.com/GenieFramework/Stipple.jl/pull/251

fix channel issue

---

src/stipple/jsintegration.jl

Fixes https://github.com/GenieFramework/StippleUI.jl/issues/123

fix parse_jsfunction()

---

src/Pages.jl
test/runtests.jl

Fix linked sessions in multipage app

---

Project.toml
src/stipple/parsers.jl
test/runtests.jl

Better support for Union types with Nothing

---

src/ReactiveTools.jl

This PR fixes #300 
I messed up my branches, so I needed to resubmit this PR

replace all variables in `@onchange` macro
