GenieFramework/Stipple.jl

src/Elements.jl
src/Stipple.jl

I tried to use the js function `this.$watch()` in `js_methods()`.
It seems that the handling of backslashes is not correct. I added a `"\\\\" => "\\"` replacement rule and now it works fine.
My use case was a watchonce method:
```
function Stipple.js_methods(HHDashboard2)
raw"""
download: function(filename) {
this.filename = filename;
// trigger the backend to calculate a string that shall be downloaded as a file
this.downloadtext = "request download";
// watch for the content to be passed in `this.downloadtext`
this.unwatch = this.\$watch("downloadtext", this.pushDownload);
},
pushDownload: function(newvalue) {
if (newvalue == "" || newvalue == "request download") { return }
var element = document.createElement('a');
element.setAttribute('href', 'data:text/plain;charset=utf-8,' + …
```

treatment of backslashes in `vue_integration()`

---

src/Layout.jl
src/Stipple.jl
src/layout/page.jl

This PR refers to #10 .
It allows for multiple instances of the same dashboard by explicitly specifying a ws channel.

allow for explicit channel specification

---

src/Stipple.jl

Currently changes in one client are reflected in the backend via the channel route "watchers" in `Stipple.init()`.
However, the changes don't trigger another broadcast inorder to prevent a ping-pong. So all other clients need to be informed by the watcher routine.
Implementation is straight forward: send a message to all connected clients except oneself.

broadcast changes to other clients

---

src/Elements.jl
src/Stipple.jl

Three points have been addressed:
- multi-user mode:
the stipple.js route has been moved to the ws channel, if the channel differs from default. This is necessary, as otherwise the data in the model definition would always use the values of the latest client that joined.
I put `@asysnc` in front of `update!(model, field, newvalue, oldvalue)` to enhance responsiveness of the server. Otherwise all observables that are triggered by the update fire and are handled before the ws channel continues. Rewind, if you think, you always want synchronous handling. We could also think about including an argument `sync` in payload...
Also for the sync reason, I moved the `update!()` after the broadcast to the other clients in multi-user-mode. 
- prevent watcher loops:
normally Vue.js's watchers always …

Improve multi-user mode, prevent watcher loops, improve payload parsing

---

Project.toml

more robust page reload by using `repr()` for the string replacement in `Stipple.Elements.jl`

Next version 0.9.1

---

src/Stipple.jl

Proposal for a modified parsing approach as solution for #68 ;
construct a wrapper around `Base.parse()` to avaoid type piracy when defining fallbacks.
Background:
I had introduced `convertvalue(targetfield, value)` because I needed to be able to use both the value and the type of the targetfield for parsing OffsetArrays. So in most cases convertvalue was already a wrapper for Base.parse. But for the fallbacks I wrote an if-clause for the different types.
I think a cleaner approach would be to handle the different types by methods of an internal parser, which I now named stippleparse. It provides a general fallback to using `Base.parse()` to cover the existing methods and defines fallbacks for arrays and dicts.
In my post above I thought you meant that we switch to only using an internal …

change parsing

---

src/Stipple.jl

If multiple ReactiveModels are present on a site, `Stipple.init()` stores only the latest `stipple_deps()` in `DEPS[Stipple]`, although the deps are model and channel-dependent. So only the page with the model that was last initialised will work whereas the other receive the wrong deps.
I propose to make the DEPS channel-dependent by allowing also Strings as a key and to include all Module deps and the deps of the respective channel that is being rendered.
Alternatively one could introduce a new constant CHANNELDEPS ...

channel-dependent DEPS

---

assets/js/watchers.js
src/Elements.jl
src/Stipple.jl

This PR is the basis for pushing single fields of dictionaries and possibly array elements in the future.
I cleaned up the `push!(model::M)` methods for this purpose.

support push of single dict fields

---

src/Stipple.jl

The current solution supplies the updated value and the vector of jskeys to the `notify()` routine.
This PR takes a more general approach and supplies a vector of pairs containing all objects (arrays or dicts) with their respective index. This makes it possible for users to write their own update functions that take into account, e.g. the index of the changed element.
Other changes:
- try-catch has been replaced by a proper `methods()` call to avoid decrease of performance.
- OffsetArrays are now handled correctly
This code could be transferred to Observables with only minor changes. I've commented [an open issue](https://github.com/JuliaGizmos/Observables.jl/issues/67) to ask if they are interested.

refactoring of element-wise updates

---

src/Layout.jl

Revert to v0.19.2 behavior where `output` was initialized as an empty string. Otherwise, cause error if `core_theme` is `false`.

fix layout typo

---

src/Elements.jl
src/Stipple.jl

Currently events are only trigger a JavaScript code provided in `v-on:*` attribute. This PR prvides a simple callback mechanism for a Julia function associated with an `v-on:*` event using same web channel used for communicating changes between a model and a view.
The native event handlers defined as overrides of `Base.notify` with two parameters a model object and a value type which contains a name of the event, e.g. `notify(model::TestModel, ::Val{:button_click})`.
The following example shows a definition of an event handler function and its wiring with `@on` macro to a button. 
```julia
module JuliaEvents
using Revise
using Stipple, StippleUI
@reactive! mutable struct TestModel <: ReactiveModel
counter::R{Int} = 0
end
function Base.notify(model::TestModel, ::Val{:button_click})
@info …
```

Native event handlers

---

src/Stipple.jl

Having a default debounce functionality is essential, but applying it to the "isready" field only slows down page loading as "isready" is called only once. 
To optimize the performance, it is wise to make the debounce feature configurable per field. However, since the model definition syntax is not yet stable (e.g., @vars vs. @handlers), for now, I suggest applying it only to the "isready" field.

Ingore denounce for isready

---

src/ReactiveTools.jl

MWE for testing:
```julia
using Stipple.ReactiveTools: ReactiveTools.DEFAULT_LAYOUT, @page, @init
using Genie.Server: up
meta = Dict("og:title" => "test", "og:description" => "genie", "og:image" => "/here/it/is")
layout = DEFAULT_LAYOUT(meta=meta)
ui() = "hi"
@page("/", ui, layout)
up()
```
Result:
Will test on GC to see if social sharing works as expected.

meta tags for default layout

---

src/ReactiveTools.jl
src/Stipple.jl
src/stipple/reactivity.jl
src/stipple/rendering.jl

This PR closes #194.
Further improvements:
- remove necessity to define Stipple.render methods with fieldname argument.
- type stability of the modes__ field
- support `import Stipple.ReactiveTools` instead of `using Stipple.ReactiveTools`

Hh precompile

---

Project.toml
ext/StippleDataFrames.jl
ext/StippleDataFramesExt.jl
ext/StippleOffsetArrays.jl
ext/StippleOffsetArraysExt.jl
ext/StippleTablesExt.jl
src/Stipple.jl
src/stipple/rendering.jl
test/runtests.jl

This PR accounts for the new extension architecture in Julia 1.9, which replaces Requires.jl
Due to errors in using Revise together with Requires in Julia 1.8.5 I have added two different extension files for 1.9 and pre-1.9:
1.9:
- StippleOffsetArraysExt.jl
- StippleDataFramesExt.jl
pre-1.9 (no modules):
- StippleOffsetArraysjl
- StippleDataFrames.jl

Add extensions for OffsetArrays and DataFrames

---

src/ReactiveTools.jl

You need to separate variables with commas in order to work. It took me some time to figure that out.

docs: onchange macro example fix

---

src/Pages.jl
src/ReactiveTools.jl
src/Stipple.jl
src/Tools.jl
src/stipple/reactivity.jl
src/stipple/rendering.jl
test/runtests.jl

Currently different methods of the `@page` macro are distinguishable only by the number of arguments, requiring the argument order `url`, `view`, `layout`, `model`, `context`.
With the new macro tool `expressions_to_args()` we can support a kwarg-like macro call, e.g.
```
model = @init
@page("/", ui, model = model)
```
for global models without the requirement to specify a layout.
EDIT: Note that the `;`-Syntax with auto duplication for kwargs is not supported in macros

support kwargs in `@page` macro

---

Project.toml
ext/StippleJSON.jl
ext/StippleJSONExt.jl
src/Stipple.jl
test/runtests.jl

Only after [fixing handling of Stipple.JSONText in StipplePlotly](https://github.com/GenieFramework/StipplePlotly.jl/commit/54f15062fc81d6385753aceea300be5478d1fc21) I understood the root cause of the error.
It is that Stipple's definition of `JSONText` for JSON3 doesn't interoperate with JSON's definition, but PlotlyBase's JSON3-rendering is calling JSON behind the scenes. Therefore, `Stipple.JSONText("test")` is rendered as `"{\"s\": \"test\"}`
```julia
julia> JSON.json(Stipple.JSONText("test"))
"{\"s\":\"test\"}"
```
This PR adds all necessary methods to JSON3 and JSON to grant interoperability of the JSONText definitions so that
```julia
julia> JSON.json(Stipple.JSONText("test"))
"test"
```
Respective tests are added to `runtests.jl`
So if in future some component adds JSON3 rendering …

interoperability for Stipple.JSONText and JSON.JSONText

---

Project.toml
ext/StippleJSONExt.jl
src/Stipple.jl
src/stipple/rendering.jl

Typical use case
```julia
using StippleUI
quasar(
:btn__toggle,
fieldname = :btn_value,
options = js_attr([opts(label = "Off", value = false), opts(label = "On", value = true)])
)
```
Furthermore, a final fix for JSONText was necessary...

add js_attr(x) for setting julia expressions as js attributes, fix JSONText in Plots

---

docs/src/API/elements.md
src/Elements.jl
test/runtests.jl

Currently we have `@iif`, `@els`, `@elsiif`and `@recur` defined due to name clashes with Julia's reserved words.
From version 1.10 on one can get around that by defining a `macro var"if"`.
However in order to be compatible, macro aliasing is a better way. So we keep the old definitions and alias them like
```julia
const var"@if" = var"@iif"
```
We even get the docstring right if we use it in the REPL:
```
help?> @if
@if(expr)
Generates v-if Vue.js code using expr as the condition. https://vuejs.org/v2/api/#v-if (https://vuejs.org/v2/api/#v-if)
Example
–––––––
julia> span("Bad stuff's about to happen", class="warning", @if(:warning))
"<span class="warning" v-if='warning'>Bad stuff's about to happen</span>"
```

rename vue attribute macros to `@if`, `@else`, `@elseif` and `@for`

---

src/Layout.jl
src/Stipple.jl

This PR addresses #231.
It requires adaptation of the respective functions in StippleUI to allow for Vectors or Dicts.
E.g. with
```julia
function btntoggle(fieldname::Symbol,
args...;
options::Union{Symbol, Vector{<:AbstractDict}},
kwargs...)
q__btn__toggle(args...; kw(
[Symbol(":options") => options, :fieldname => fieldname, kwargs...])...)
end
```
we could write
```julia
julia> import Stipple.opts
julia> btntoggle(:network, options = [opts(label = x, value = lowercase(x)) for x in ("Google", "Facebook")])
"<q-btn-toggle v-model=\"network\" :options=\"[{'value':'google','label':'Google'},{'value':'facebook','label':'Facebook'}]\"></q-btn-toggle>"
julia> select(:selector, options = ["a", "b", "c"],)
"<q-select v-model=\"selector\" :options=\"['a','b','c']\"></q-select>"
```

add automatic json conversion for attributes

---

src/Pages.jl
test/runtests.jl

Currently, routing of ParsedHTMLString is broken in two ways:
- ParsedHTMLValues and vectors thereof are not correctly handled by `html()`; layout and model are ignored
- content of functions that generate ParsedHTML or vectors thereof is parsed; it is therefore impossible to route content that is not correctly parsed, e.g. `'@'` characters (cf. https://github.com/GenieFramework/Stipple.jl/issues/164)
This PR fixes both shortcomings together with a respective fix in Genie.

fix handling of ParsedHTML in `@page` macro

---

assets/js/watchers.js
src/Elements.jl
src/ReactiveTools.jl
src/Stipple.jl
src/stipple/rendering.jl

I refactored the Genie's reviver for easier implementation of user-defined revivers. (https://github.com/GenieFramework/Genie.jl/pull/690)
Users can now use the javascript function `Genie.addReviver(f)`
This makes the construction of a StippleMathjs.jl (see https://github.com/GenieFramework/Stipple.jl/issues/235) very easy.
-------------------
This solution was greatly inspired by https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse

refactor reviver

---

assets/js/watchers.js
src/Elements.jl
src/Stipple.jl
src/stipple/jsintegration.jl

Currently, it is not possible to address single clients by push! or run commands.
To remedy this situation I propose to
- modify existing keyword `except` to support not only UInt, but also Vetor{UInt} to exclude more than one client
- remove `WebSocket` as a possible value for except and rather supply the id as it is done in WebThreads
- add a keyword `restrict` to restrict messages to a client or list of clients
There will be a corresponding PR in Genie.

Support except and restrict in `push!()` and run()`

---

src/Stipple.jl

Fixes https://github.com/GenieFramework/Stipple.jl/issues/242
It reverts one of the changes made as part of [this commit](https://github.com/GenieFramework/Stipple.jl/commit/6aeeba96e5d4d2fdaea6dcc699304167b3e064cc#diff-39019d8ae899bcdd3758db28f205d5c546be80ab59858397e829ce82fa2e9f38), where key Router.params() key `:SESSION` has been replaced with `:session`. 
This has caused problems downstream with GenieAuthentication.

Fix invalid session key

---

src/Layout.jl
src/ReactiveTools.jl

This PR has two parts:
- accept AbstractStrings and Vectors for head_content
- accept head_content in DEFAULT_LAYOUT
```julia
cesium_head = [
script(src = "https://cesium.com/downloads/cesiumjs/releases/1.113/Build/Cesium/Cesium.js", ),
link(href = "https://cesium.com/downloads/cesiumjs/releases/1.113/Build/Cesium/Widgets/widgets.css", rel = "stylesheet", )
]
route("/") do
page(@init, ui, head_content = cesium_head)
end
@page("/", ui, Stipple.ReactiveTools.DEFAULT_LAYOUT(head_content = cesium_head))
```
Note: for the latter version to work, you have to delay a potential init script if it refers to DOM elements until they are visible, typically, when the app is ready. `js_initscript` is a wrapper, that executes code after the webtransport is subscribed.
```julia
cesium_module_text = """ …
```

more options for head_content

---

src/Stipple.jl
src/stipple/print.jl

model printing is currently not easy to understand at the REPL, Garish.pprint doesn't improve the situation a lot
This PR implements automatic prettyprinting at the REPL:
```julia
julia> @app begin
@out non_reactive a_::Int = 12
@out s_ = "Hello"
@out f = jsfunction"console.log('Hi')"
end
__GF_AUTO_HANDLERS__ (generic function with 1 method)
julia> @init
Instance of 'Main_ReactiveModel'
channel_ (internal): JUURVSVWBPYQFUNBDYIEDYVCFGCTUEFG
channel__ (internal): JUURVSVWBPYQFUNBDYIEDYVCFGCTUEFG
modes__ (internal): LittleDict(:a_ => 4)
isready (autofield, in): false
isprocessing (autofield, out): false
fileuploads (autofield, in): Dict{AbstractString, AbstractString}()
a_ (out, non-reactive): 12
s_ (out): Hello
f (out): Dict{Symbol, Any}(:jsfunction => Dict{Symbol, Any}(:body => …
```

add prettyprinting of models

---

src/ReactiveTools.jl
src/Stipple.jl
test/runtests.jl

This PR address #186 and adds the possibility of adding field-specific debounce times via
```julia
@debounce myfield 10
@debounce MyApp myfield 10
@clear_debounce myfield
@clear_debounce MyApp myfield
@clear_debounce 
@clear_debounce MyApp
Stipple.debounce(MyApp, :myfield, 10)
Stipple.debounce(MyApp, :myfield, nothing)
```
tests and docstrings are provided

add field-specific debouncing

---

src/Stipple.jl

The setup in Stipple is such that each client receives its own model and that model is connected via a channel. But different clients that use the same channel don't really use different models. Instead they are using only the latest model they write to and that they receive data from. The respective part of code is here.
(https://github.com/GenieFramework/Stipple.jl/blob/master/src/Stipple.jl#L533).
However, the event channel is not always updated to use the latest model due to the [following condition](https://github.com/GenieFramework/Stipple.jl/blob/master/src/Stipple.jl#L622) 
```julia
if ! Genie.Router.ischannel(Router.channelname(ch))
```
Unfortunately, this is not only critical for multi-clients but also in case of page reloading.
After reloading the page the watchers act on the …

fix diverging models in watcher and event channels

---

src/Elements.jl
src/Layout.jl
src/Stipple.jl
test/runtests.jl

Support Quasar's q-gutter / q-col-gutter by adding three new flexgrid kwargs `gutter`, `xgutter` and `ygutter`.
Depeneding on whether the element is a container (`row`or `column`) it chooses the correct gutter setting in class:
```julia
julia> row(gutter = :md, @gutter [
card("Hello", sm = 12, lg = 4)
card("World", sm = 12, md = 8)
]) |> prettify |> println
<div class="row col q-col-gutter-md">
<div class="col col-sm-12 col-lg-4">
<q-card>
Hello
</q-card>
</div>
<div class="col col-sm-12 col-md-8">
<q-card>
World
</q-card>
</div>
</div>
```
or 
```julia
julia> htmldiv(@gutter :md [
card("Hello", sm = 12, lg = 4)
card("World", sm = 12, md = 8)
]) |> prettify |> println
<div class="q-gutter-md">
<div class="col-sm-12 col-lg-4">
<q-card>
Hello
</q-card>
</div>
<div class="col-sm-12 …
```

support gutter by `@gutter` and flexgrid kwarg `gutter`

---

src/stipple/parsers.jl
test/runtests.jl

Add automatic struct parsing for both normal structs and structs defined by `@kwdef`:
```julia
struct HH1
c::Int
d::Int
end
struct HH2
a::Int
b::HH1
end
hh2 = HH2(1, HH1(2, 3))
hh2_dict = JSON3.read(json(hh2), Dict)
Base.@kwdef struct T1
c::Int = 1
d::Int = 3
end
Base.@kwdef struct T2
a::Int = 1
b::T1 = T1()
end
Stipple.stipple_parse(HH2, hh2_dict)
Stipple.stipple_parse(T1, Dict())
Stipple.stipple_parse(T2, Dict())
```

stipple_parse structs

---

src/Stipple.jl
src/stipple/rendering.jl

removing `julia_to_vue()` fixes #275 
making the OptDict an OrderedDict keeps the ordering of attributes, which is definitely a good thing and which removes the necessity to define another attributes function in StipplePlotly, where ordering was required.

remove julia_to_vue, make OptDict an OrderedDict

---

src/Layout.jl
src/ReactiveTools.jl

Currently, when `theme()` is called once, the coretheme is added to `THEMES[]`.
This is a bit unfortunate, because you first have to remove it manually if you want to render a page without core_theme. Moreover, parallel pages with and without core_theme are difficult to maintain. As theme() is anyhow called in order to append all stylesheets to the page, we can rely on the keyword attribute. Currently it's always added and then removed by `unique!()` if it was present before. Moreover, I made it a named function make it more understandable.

never add core_theme to THEMES

---

src/Stipple.jl

Details
- set secret before precompilation and reset afterwards to prevent precompilation error
- suppress server output during precompilation

fix precompilation error, suppress output

---

src/Stipple.jl
src/Tools.jl

This PR strongly simplifies the writing of a precompile section for Stipple apps.
Stipple.jl itself now uses the new macro `@stipple_precompile` to precompile functions for typical usage. The previous defintion has come down to.
```julia
@stipple_precompile begin
ui() = [cell("hello"), row("world"), htmldiv("Hello World")]
@app PrecompileApp begin
@in demo_i = 1
@out demo_s = "Hi"
@onchange demo_i begin
println(demo_i)
end
end
route("/") do 
model = Stipple.ReactiveTools.@init PrecompileApp
page(model, ui) |> html
end
precompile_get("/")
deps_routes(core_theme = true)
precompile_get(Genie.Assets.asset_path(assets_config, :js, file = "stipplecore"))
end
```
and all previous of spinning up a server which doesn't spill the precompilation output and checking whether server requests should be …

add `@stipple_precompile` for easier precompilation of user apps

---

src/Stipple.jl
src/stipple/reactivity.jl

This PR together with https://github.com/GenieFramework/Genie.jl/pull/723 fix #297

add autofield :ws_disconnected

---

src/ModelStorage.jl
src/Stipple.jl
test/runtests.jl

I've also changed the include order in Stipple.jl since these functions need the `INTERNALFIELDS, AUTOFIELDS`in order to determine which model fields should not be exported.

Added functions for exporting and importing model field values from Dict

---

assets/js/keepalive.js
assets/js/watchers.js
src/Elements.jl
src/Layout.jl
src/Stipple.jl
src/stipple/jsmethods.jl
src/stipple/rendering.jl
test/runtests.jl

This PR fixes at least part of what was requested in https://github.com/GenieFramework/Stipple.jl/issues/171.
It goes together with a respective PR in Genie.
We now support multiple models on a single page, even models of the same type.
Each model has its own websocket connection, with its own keepalive timer and ws_disonnected field.
The reconnection loop issue has also been fixed.
MWE:
```jullia
using Stipple, Stipple.ReactiveTools
using StippleUI
@app MyApp1 begin
@in i = 0
@onchange i begin
@notify("i has changed $i")
end
end handlers1
@app MyApp2 begin
@in j = 0
@onchange j begin
@notify("j has changed $j")
end
end handlers2
@app MyApp3 begin
@in k = 0
@onchange k begin
@notify("k has changed $k")
end
end handlers3
ui(field = :i) = () -> row(card([
cardsection(h6("Websocket …
```

Support multi-model pages

---

src/Pages.jl
src/ReactiveTools.jl
src/Stipple.jl

Currently there is no way of authentication implemented in the ReactiveTools API, nor a way of manipulating models directly after instantiation.
This PR impplements a routehandler that can be the base of both. It is defined to be `nothing` per default.
```julia
routehandler(model::ReactiveModel, ::Any) = routehandler(model)
routehandler(::ReactiveModel) = nothing
```
It is called by the Page action directly after model initialisation.
If the result is not `nothing` the return value of the routehandler is returned, otherwise the standard page is delivered.
```julia
@app MyApp begin
@in dt = 1
end
@page("/", "Hello world", model = MyApp)
@page("/test", "Hello test", model = MyApp)
Stipple.routehandler(::MyApp) = println("route: ", params(:ROUTE).path, "\nsession: ", …
```

add Pages.routehandler

---

src/ReactiveTools.jl
src/Stipple.jl
src/stipple/components.jl
src/stipple/jsmethods.jl
src/stipple/rendering.jl

Writing and registering Vue components has been a bit tedious in the past.
With this - rather small - PR we can use normal app syntax to write and register Vue components:
```julia
using Stipple, Stipple.ReactiveTools
using StippleUI
import Stipple.opts
@app VueCopyButton begin
@out copied = false
end
@methods VueCopyButton [
:handleCopy => js"""function () {
const text = typeof this.text === 'function' ? this.text() : this.text;
Quasar.copyToClipboard(text).then(() => {
this.copied = true;
setTimeout(() => {
this.copied = false;
}, 700);
});
}
"""
]
@props VueCopyButton opts(
text = opts(
type = [js"String", js"Function"],
required = true
)
)
@template VueCopyButton btn(
icon = R"this.copied ? 'check' : 'content_copy'",
aria__label = R"this.copied ? 'Copied!' : 'Copy to clipboard'",
flat …
```

Generate Vue components from apps
